### ISSUE TITLE
Cyborg cuffs need to be fixed.

### ISSUE THREAD

**Issue by C0rva1r** [privateroleplaysociety/odessa-outpost#66]
Currently impossible to remove cuffs due to a bug. 

Might be easily be fixed but until it is fixed, going to leave a note here about it.

**Comment by rpilcrow** [comment]
Seems to be triggered by handcuffs with dispenser = 1, which creates a new pair of handcuffs and applies those when cuffing a target, rather than applying the handcuffs themselves.
What differs between new cuffs and 'old' cuffs I don't know yet. Will look into.

**Comment by rpilcrow** [comment]
Discovered today that handcuffs applied normally have an equip_slot of 4 or 5, depending on which hand you used to apply them. 'Stuck' cuffs have an equip_slot of 0, as they are newly spawned and their equip_slot is never set.
Changing a stuck pair of cuff's equip_slot to 3, 4, or 5 will allow them to be removed without issue. (3 correlates to the actual 'handcuffs' slot.)

Obviously, somewhere along the lines equip_slot just isn't being set for handcuffs, and the only reason they can be removed at all currently is because they specifically have been handled by a player and are carrying their equip_slot value over.
